// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfuDDYj9CcJpua7LBq8PlGTvaaWocC8Qc',
    appId: '1:251620269362:web:c3ab28cd561afa518b8b2b',
    messagingSenderId: '251620269362',
    projectId: 'personal-expense-tracker-735ad',
    authDomain: 'personal-expense-tracker-735ad.firebaseapp.com',
    storageBucket: 'personal-expense-tracker-735ad.firebasestorage.app',
    measurementId: 'G-R3EG14T6SC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvR0t909GwyKMORpRaIWGDpnal4puc52c',
    appId: '1:251620269362:android:c9beda84e0bcf1928b8b2b',
    messagingSenderId: '251620269362',
    projectId: 'personal-expense-tracker-735ad',
    storageBucket: 'personal-expense-tracker-735ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMn0XcMWL20zHZ62aLBT4fn494LV-9NJE',
    appId: '1:251620269362:ios:02bf112ed1c994458b8b2b',
    messagingSenderId: '251620269362',
    projectId: 'personal-expense-tracker-735ad',
    storageBucket: 'personal-expense-tracker-735ad.firebasestorage.app',
    iosBundleId: 'com.example.newapp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfuDDYj9CcJpua7LBq8PlGTvaaWocC8Qc',
    appId: '1:251620269362:web:663e92db1f00c7e38b8b2b',
    messagingSenderId: '251620269362',
    projectId: 'personal-expense-tracker-735ad',
    authDomain: 'personal-expense-tracker-735ad.firebaseapp.com',
    storageBucket: 'personal-expense-tracker-735ad.firebasestorage.app',
    measurementId: 'G-EZPWRRVZ32',
  );
}
